#!/bin/bash

set -e
[ "$EUID" -gt 0 ] && exec sudo $0 $@


read -p "RIT username: " USER
read -s -p "RIT password: " PASSWORD
IFACE=`ip link | grep -- '^2:' | awk '{print $2;}' | cut -d: -f1`
MAC=`ip link show $IFACE | grep link/ether | awk '{print $2;}'`

cat <<EOF > /etc/NetworkManager/system-connections/ritwpa2
[ipv6]
method=auto

[connection]
id=ritwpa2
uuid=cc3b4d5f-2b7a-40bf-9c5b-ced3cadb22fa
type=802-11-wireless

[802-11-wireless]
ssid=ritwpa2
mode=infrastructure
mac-address=$MAC
security=802-11-wireless-security

[802-1x]
eap=peap;
identity=$USER
phase2-auth=mschapv2
password=$PASSWORD

[ipv4]
method=auto

[802-11-wireless-security]
key-mgmt=wpa-eap
auth-alg=open

EOF

chmod 600 /etc/NetworkManager/system-connections/ritwpa2

systemctl stop NetworkManager.service
killall wpa_supplicant
pidof dhclient > /dev/null && dhclient -r $IFACE
while ( pidof NetworkManager || pidof wpa_suppliant ) > /dev/null ; do
	sleep 0.2
done
systemctl start NetworkManager.service
